# Generated by Django 5.0.6 on 2024-07-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrauserdata',
            name='birth_date',
            field=models.DateField(default='1999-01-01'),
            preserve_default=False,
        ),
    ]
