# Generated by Django 5.0.6 on 2024-06-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='document',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
