# Generated by Django 5.0.6 on 2024-07-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_xray',
            field=models.ImageField(blank=True, null=True, upload_to='xrays'),
        ),
    ]
