# Generated by Django 5.0.6 on 2024-07-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_last_xray'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='last_xray',
            field=models.ImageField(blank=True, null=True, upload_to='xrays/'),
        ),
    ]
